### ISSUE TITLE
Hey! 

### ISSUE THREAD

**Issue by ghost** [wiafe/Test#1]
Hey dude!

Dain here from starthere.fm I saw your comment on our episode and wanted to peep some of your work. I hope you get the email notifications from github ;)

:+1: Let's do it though, we'd love the help. We decided to build the site custom from the ground up, so if you really earnestly want to join the build let me know and I'll see if we can actually get you involved in most of it as it happens here over the next few weeks and months.

Peace bro!

**Comment by wiafe** [comment]
Yeah, I'm down to help! Just let me know when and where. :D

**Comment by ghost** [comment]
Awesome! I'll be in touch!

**Comment by ghost** [comment]
:+1:
